name: Deploy to VPS

on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME || 'htmlonelove' }}   # User for GHCR
  DOCKER_REPO: ${{ vars.DOCKER_REPO || 'liga-nextjs-template' }}  # Repo name
  DOCKER_IMAGE: ghcr.io/${{ vars.DOCKER_USERNAME || 'htmlonelove' }}/${{ vars.DOCKER_REPO || 'liga-nextjs-template' }}:latest  # Full image name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: SSH config to VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to VPS
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << EOF
            export DOCKER_IMAGE="${{ env.DOCKER_IMAGE }}"
            echo "Pulling image: \$DOCKER_IMAGE"
            docker pull \$DOCKER_IMAGE
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 \$DOCKER_IMAGE
          EOF

      # Step 4: Configure Nginx
      - name: Configure Nginx
        run: |
          scp -o StrictHostKeyChecking=no ./nginx.conf ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/tmp/nginx.conf
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << EOF
            sudo mv /tmp/nginx.conf /etc/nginx/sites-available/nextjs-app
            sudo ln -sf /etc/nginx/sites-available/nextjs-app /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo systemctl restart nginx
          EOF
